# Generated by Django 3.1.1 on 2020-11-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20201016_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='munchcart',
            name='cafe_name',
            field=models.CharField(default='Munch', max_length=120),
        ),
        migrations.AddField(
            model_name='tangocart',
            name='cafe_name',
            field=models.CharField(default='Tango', max_length=120),
        ),
        migrations.AddField(
            model_name='udupicart',
            name='cafe_name',
            field=models.CharField(default='Udupi', max_length=120),
        ),
    ]
