# Generated by Django 3.1.1 on 2020-11-05 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20201016_1142'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunchOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(default='created', max_length=120)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('munch_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.munchcart')),
            ],
        ),
        migrations.CreateModel(
            name='TangoOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(default='created', max_length=120)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('tango_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.tangocart')),
            ],
        ),
        migrations.CreateModel(
            name='UdupiOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(default='created', max_length=120)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('udupi_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.udupicart')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
