# Generated by Django 3.1.1 on 2020-11-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201105_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='munchorder',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tangoorder',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='udupiorder',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
