# Generated by Django 3.1.1 on 2020-11-28 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20201128_1624'),
        ('orders', '0003_auto_20201128_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='munchorder',
            name='billing_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.munchbillingprofile'),
        ),
        migrations.AddField(
            model_name='tangoorder',
            name='billing_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.tangobillingprofile'),
        ),
        migrations.AddField(
            model_name='udupiorder',
            name='billing_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.udupibillingprofile'),
        ),
    ]
