# Generated by Django 3.1.1 on 2020-11-28 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20201128_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='munchorder',
            old_name='munch_cart',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='tangoorder',
            old_name='tango_cart',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='udupiorder',
            old_name='udupi_cart',
            new_name='cart',
        ),
    ]
