# Generated by Django 3.1.1 on 2020-09-15 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_udupi_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Tango_Products',
        ),
        migrations.RenameModel(
            old_name='Udupi_Product',
            new_name='Udupi_Products',
        ),
    ]
