# Generated by Django 3.1.1 on 2020-12-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200915_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='munch',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='tango',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='udupi',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
